// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DatePickerDay: typeof import('./components/datatypes/DatePickerDay.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    FormProfile: typeof import('./components/FormProfile.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    'IMdi:account': typeof import('~icons/mdi/account')['default']
    'IMdi:calendar': typeof import('~icons/mdi/calendar')['default']
    'IMdi:checkboxMarkedCircle': typeof import('~icons/mdi/checkbox-marked-circle')['default']
    'IMdi:delete': typeof import('~icons/mdi/delete')['default']
    'IMdi:edit': typeof import('~icons/mdi/edit')['default']
    'IMdi:fire': typeof import('~icons/mdi/fire')['default']
    'IMdi:weight': typeof import('~icons/mdi/weight')['default']
    IParkPlusCross: typeof import('~icons/icon-park/plus-cross')['default']
    Profiles: typeof import('./components/Profiles.vue')['default']
    ProfileViewMain: typeof import('./components/ProfileViewMain.vue')['default']
    'ProfileViewMain.chartDoughnutOK': typeof import('./components/ProfileViewMain.chart-doughnut-OK.vue')['default']
    'ProfileViewMain.chartLineOK': typeof import('./components/ProfileViewMain.chart-line-OK.vue')['default']
  }
}

export { }
